#
# Agent based Simulation
# Makefile
#
#
# 08 - Nov - 2009  VEC     init
#

################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= oclAgents
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= oclAgents.cpp

################################################################################
# Rules and targets

include ../../common/common_opencl.mk
